@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package compasses.expandedstorage.forge.datagen.providers;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
