@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package compasses.expandedstorage.impl.datagen.providers;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
