modLoader = "kotlinforforge"
loaderVersion = "[4.10,)"
issueTrackerURL = "https://github.com/quinn-semele/expanded-storage/issues/"
license = "Apache-2.0"

[[mods]]
modId = "stowage"
version = "${version}"
displayName = "Stowage"
description = "A storage mod focusing on UX."
authors = "Quinn Semele"
logoFile = "icon.png"

[[dependencies.stowage]]
modId = "neoforge"
type = "required"
versionRange = "[20.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stowage]]
modId = "minecraft"
type = "required"
versionRange = "24w10a"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "stowage-common.mixins.json"