modLoader = "javafml"
loaderVersion = "${fml_version_constraint}"
license = "${license}"
issueTrackerURL = "https://github.com/Ghost/example-mod/issues"
[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/example-mod"
logoFile = "${mod_id}.png"
credits = "${credits}"
authors = "${nf_authors}"
description = "${description}"
[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"
[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${nf_minecraft_constraint}"
ordering = "NONE"
side = "BOTH"